Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Guilherme
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Leonardo De Oliveira Julião
// Data atual  : 27/04/2026
Var
// Seção de Declarações das variáveis 
nome: caractere
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Hello World")
   escreval("Bem-Vindo ao Senac Barretos")
   
   escreval("Nome do usuário? Leonardo De Oliveira Julião")
   escreval("Qual a idade? 27 anos")
   
   escreval("Digite seu nome: ")
   leia(nome)

Fimalgoritmo