Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/04/2026
Var
cor: caractere


Inicio
escreval ("O semáfora está Verde ou Vermelho?")
leia (cor)

se (cor = "Verde") entao
escreval ("Siga em frente!")
senao
se(cor = "Vermelho") entao
escreval ("Pare o carro!")
senao
escreval (cor = "Digite novamente")
fimse
fimse


Fimalgoritmo