Algoritmo "Leia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Guilherme
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Leonardo De Oliveira Julião
// Data atual  : 27/04/2026
Var
// Seção de Declarações das variáveis 
nome: caractere
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite seu nome: ")
leia(nome)
escreval("Olá ", nome, ", seja bem vindo ao Senac Barretos.")

escreval("Digite sua idade: ")
leia(idade)
escreval("Bom saber que você tem", idade," anos de idade.")

Fimalgoritmo