Algoritmo "Cálulos Matemáticos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/04/2026
Var
// Inserção das variáveis
Numero1, Numero2, Resultado: real

Inicio
// Entrada de dados
escreval ("----------CALCULADORA DE VALORES----------")

escreval("Digite o primeiro número: ")
leia(Numero1)

escreval("Digite o segundo número: ")
leia(Numero2)

// Processamento do resultado

Resultado <- Numero1 + Numero2

escreval("O resultado da somatória é ", Resultado)

Fimalgoritmo