Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/04/2026
Var
// Seção de Declarações das variáveis 
e_maior: logico
idade: inteiro

Inicio
escreva ("Digite sua idade: ")
leia (idade)

e_maior <- idade > 17

escreval ("É maior: ", e_maior)

Fimalgoritmo