Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/04/2026
Var
// Seção de Declarações das variáveis 
senha: inteiro
autorizado: logico


Inicio
escreval ("Digite a senha: ")
leia(senha)

autorizado <- senha = 1234

escreval ("Senha correta", autorizado)


Fimalgoritmo