Algoritmo "Atividade 1 - 25-05-2026"

Var
numero: inteiro



Inicio
escreval ("Abra a caixa, sorteie um número de 1 à 100 e veja se recebeu um item lendário!")
escreval("-----------------------------------------------------------------")
escreva ("Digite o número sorteado:")
leia (numero)
limpatela

se numero >= 80 entao
    escreval ("Parabéns, você recebeu um item lendário!")
    senao
    escreval ("Você recebeu um item comum!")
fimse




Fimalgoritmo