Algoritmo "Atividade 6 - 18-05-2026"

Var
mes: inteiro


Inicio

escreval ("Qual mês escolhido para descobrir a quantidade de dias?")
escreval ("-------------------------------------------------------------")
escreval ("1 - Janeiro")
escreval ("2 - Fevereiro")
escreval ("3 - Março")
escreval ("4 - Abril")
escreval ("5 - Maio")
escreval ("6 - Junho")
escreval ("7 - Julho")
escreval ("8 - Agosto")
escreval ("9 - Setembro")
escreval ("10 - Outubro")
escreval ("11 - Novembro")
escreval ("12 - Dezembro")
escreval ("-------------------------------------------------------------")

leia (mes)

limpatela

escolha mes
    caso 1
        escreval ("O mês de Janeiro possui 31 dias!")
    caso 2
        escreval ("O mês de Faneiro possui 28 ou 29 dias se for ano bisexto!")
    caso 3
        escreval ("O mês de Março possui 31 dias!")
    caso 4
        escreval ("O mês de Abril possui 30 dias!")
    caso 5
        escreval ("O mês de Maio possui 31 dias!")
    caso 6
        escreval ("O mês de Junho possui 30 dias!")
    caso 7
        escreval ("O mês de Julho possui 31 dias!")
    caso 8
        escreval ("O mês de Agosto possui 31 dias!")
    caso 9
        escreval ("O mês de Setembro possui 30 dias!")
    caso 10
        escreval ("O mês de Outubro possui 31 dias!")
    caso 11
        escreval ("O mês de Novembro possui 30 dias!")
    caso 12
        escreval ("O mês de Desembro possui 31 dias!")
    outrocaso
        escreval ("Digitação incoerente! Escolha um número!")
fimescolha


Fimalgoritmo