Algoritmo "Atividade 6 - 18-05-2026"

Var
mes: caractere

Inicio

escreval ("Qual mês escolhido para descobrir a quantidade de dias?")
leia (mes)

limpatela

se (mes = "abril") ou (mes = "junho") ou (mes = "setembro") ou (mes = "novembro") entao
escreval ("Nº de dias: 30 dias")
senao
se (mes = "Abril") ou (mes = "Junho") ou (mes = "Setembro") ou (mes = "Novembro") entao
escreval ("Nº de dias: 30 dias")
senao
se (mes = "fevereiro") entao
escreval ("Nº de dias: 28/29 dias")
senao
se (mes = "Fevereiro") entao
escreval ("Nº de dias: 28/29 dias")
senao
escreval ("Nº de dias: 31 dias")

fimse
fimse
fimse
fimse

Fimalgoritmo