Algoritmo "Atividade 4 - 04-05-2026"

Var
Prova_1: real
Prova_2: real
Prova_3: real
media_provas: real

Inicio
escreval ("Digite a nota de sua 1ª prova: ")
leia (Prova_1)

escreval ("Digite a nota de sua 2ª prova: ")
leia (Prova_2)

escreval ("Digite a nota de sua 3ª prova: ")
leia (Prova_3)

media_provas <- (prova_1 + prova_2 + prova_3) / 3

escreval ("Sua média das 3 últimas provas é: ", media_provas:1:2 ,".")

Fimalgoritmo