Algoritmo "Atividade 12 - 05-05-2026"



Var
numero1: real
numero2: real
tamanho: logico



Inicio
escreval ("Digite 2 números e veja qual é o maior")
         escreva ("Digite o 1º número: ")
                 leia (numero1)

         escreva ("Digite o 2º número: ")
                 leia (numero2)

                 se (numero1 > numero2) entao
                 escreval ("Número 1 é o maior!")

                 senao (numero2 > numero1)
                 escreval ("Número 2 é o maior!")
                 fimse




Fimalgoritmo